// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewInstance(arg1, arg2) {
  return window['go']['main']['App']['CreateNewInstance'](arg1, arg2);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function GetAppVersion(arg1) {
  return window['go']['main']['App']['GetAppVersion'](arg1);
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function Launch(arg1) {
  return window['go']['main']['App']['Launch'](arg1);
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function RepairInstance(arg1) {
  return window['go']['main']['App']['RepairInstance'](arg1);
}

export function RequestPermissions() {
  return window['go']['main']['App']['RequestPermissions']();
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}

export function UpdateInstance(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateInstance'](arg1, arg2, arg3);
}
