// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNewInstance(arg1:string,arg2:string):Promise<string>;

export function DeleteInstance(arg1:string):Promise<string>;

export function GetAppVersion(arg1:string):Promise<string>;

export function GetInstances():Promise<Array<main.Instance>>;

export function Launch(arg1:string):Promise<void>;

export function OpenBrowser(arg1:string):Promise<void>;

export function RepairInstance(arg1:string):Promise<string>;

export function RequestPermissions():Promise<void>;

export function StopInstance(arg1:string):Promise<string>;

export function UpdateInstance(arg1:string,arg2:string,arg3:string):Promise<string>;
